### ISSUE TITLE
URI undefined

### ISSUE THREAD

**Issue by rybit** [sensu-plugins/sensu-plugins-ssl#27]
Hi - I recently upgraded sensu to version 29 and it seems to have broken one of my checks:

```
$ /opt/sensu/embedded/bin/check-ssl-qualys.rb -d netlify.com
```

It seems to be the line (but I am not an expert at ruby to say the least)
```
    uri       = URI("#{config[:api_url]}analyze")
```
The warning is:
```
Check failed to run: undefined method `URI' for #<CheckSSLQualys:0x00000001ea15b8>, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ssl-1.3.0/bin/check-ssl-qualys.rb:93:in `ssl_api_request'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ssl-1.3.0/bin/check-ssl-qualys.rb:103:in `ssl_check'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ssl-1.3.0/bin/check-ssl-qualys.rb:110:in `block in ssl_recheck'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ssl-1.3.0/bin/check-ssl-qualys.rb:109:in `upto'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ssl-1.3.0/bin/check-ssl-qualys.rb:109:in `ssl_recheck'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ssl-1.3.0/bin/check-ssl-qualys.rb:118:in `ssl_grades'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ssl-1.3.0/bin/check-ssl-qualys.rb:124:in `lowest_grade'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ssl-1.3.0/bin/check-ssl-qualys.rb:128:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

I was wondering if anything had changed in the version upgrade? I am running version 2.4.0 afaict

**Comment by eheydrick** [comment]
Looks like the switch from `rest-client` to `net-http` in 1e3ecc292df39ca044f5ec9373b3b0a7184bf398 broke the check. I think I see why and will come up with a fix.

**Comment by eheydrick** [comment]
The issue is `net-http` was never required in the move from `rest-client` to `net/http` and the `URI` method was not available. I have a fix in #28.

**Comment by majormoses** [comment]
Sorry this got past me, I should have pulled it down to test. Cost of not having tests...

**Comment by majormoses** [comment]
@rybit also as a side note we need to add ruby 2.4 testing as 0.29 uses this now and we do not currently have coverage. I will fix this when I have some time.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-ssl/versions/1.3.1

**Comment by rybit** [comment]
awesome. Thanks for the rapid fix! I knew I could just ask and this would get sorted out! :)
