### ISSUE TITLE
Gemnasium badge is broken

### ISSUE THREAD

**Issue by rwky** [sensu-plugins/sensu-plugins-ssl#40]
Can be fixed via gitlab docs here https://docs.gitlab.com/ee/user/project/import/gemnasium.html

Probably best a project owner does this.

**Comment by betorvs** [comment]
Hi @rwky i trying to compile this plugins using travis and bonsai, but Im receiving this error:
```
Failures:
  1) CheckSSLHSTSPreloadable should pass check if the domain is preloadedable but has warnings
     Failure/Error: expect(check).to receive(:warning).and_raise SystemExit
```
Can you help me? 
Im using an fork of these repository: https://github.com/betorvs/sensu-plugins-ssl/
Complete logs: https://travis-ci.org/betorvs/sensu-plugins-ssl/jobs/624672423

**Comment by rwky** [comment]
@betorvs it's because of https://github.com/chromium/hstspreload/issues/114 which is an upstream issue.
